version: "2"

services:
   multiroomaudio:
     image: s1lvester/docker-snapcast-multiroomaudio
     environment:
       SPOTIFY_BITRATE: 160
       SPOTIFY_NAME: Snapcast
     networks:
       mylan:
         ipv4_address: # desired address for container e.g. 192.168.5.80
     
networks:
  mylan:
    external: true
